// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMNPa4IVGr5i1U8gtPWMov21dAI-kJxJw',
    appId: '1:894883712149:web:da719e1386c9a57bbd1f9c',
    messagingSenderId: '894883712149',
    projectId: 'restaurant-waste-app-75ce6',
    authDomain: 'restaurant-waste-app-75ce6.firebaseapp.com',
    storageBucket: 'restaurant-waste-app-75ce6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfcanXx69W_cBEC_MUrokCpsPlCsRV54A',
    appId: '1:894883712149:android:5710f644d9c2ac21bd1f9c',
    messagingSenderId: '894883712149',
    projectId: 'restaurant-waste-app-75ce6',
    storageBucket: 'restaurant-waste-app-75ce6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYDR5PnGTZ25pU6EyGVmhph-uVNoPqZG4',
    appId: '1:894883712149:ios:bcb10e2f672aa251bd1f9c',
    messagingSenderId: '894883712149',
    projectId: 'restaurant-waste-app-75ce6',
    storageBucket: 'restaurant-waste-app-75ce6.firebasestorage.app',
    androidClientId: '894883712149-hd20q97449mkl92f9rc3v9eoc0ht0i8u.apps.googleusercontent.com',
    iosClientId: '894883712149-67eh8ohfne9ipcf9mff6o5a09f6sffpg.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurantFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYDR5PnGTZ25pU6EyGVmhph-uVNoPqZG4',
    appId: '1:894883712149:ios:bcb10e2f672aa251bd1f9c',
    messagingSenderId: '894883712149',
    projectId: 'restaurant-waste-app-75ce6',
    storageBucket: 'restaurant-waste-app-75ce6.firebasestorage.app',
    androidClientId: '894883712149-hd20q97449mkl92f9rc3v9eoc0ht0i8u.apps.googleusercontent.com',
    iosClientId: '894883712149-67eh8ohfne9ipcf9mff6o5a09f6sffpg.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurantFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMNPa4IVGr5i1U8gtPWMov21dAI-kJxJw',
    appId: '1:894883712149:web:85a40b6e84fda2febd1f9c',
    messagingSenderId: '894883712149',
    projectId: 'restaurant-waste-app-75ce6',
    authDomain: 'restaurant-waste-app-75ce6.firebaseapp.com',
    storageBucket: 'restaurant-waste-app-75ce6.firebasestorage.app',
  );

}